export const popularTemplates = [
  {
    id: 1,
    name: "Alex Berman Pattern Interrupt",
    nameAr: "نمط أليكس بيرمان - كسر النمط",
    badge: "Most Popular",
    author: "Alex Berman",
    description: "Research-based opener with pattern interrupt",
    descriptionAr: "افتتاحية قائمة على البحث مع كسر النمط",
    emails: 5,
    days: 10,
    schedule: [0, 3, 5, 7, 10],
    stats: {
      avgOpenRate: 23.4,
      avgReplyRate: 8.2,
      usedCount: 2456,
    },
    structure: [
      { day: 0, subject: "Research-based compliment + question", type: "pattern_interrupt" },
      { day: 3, subject: "Value offer with case study", type: "value" },
      { day: 5, subject: "Social proof", type: "social_proof" },
      { day: 7, subject: "Different angle", type: "angle_shift" },
      { day: 10, subject: "Permission-based breakup", type: "breakup" },
    ],
    bestFor: ["B2B", "SaaS", "Agencies"],
    difficulty: "intermediate",
  },
  {
    id: 2,
    name: "Case Study Sequence",
    nameAr: "تسلسل دراسة الحالة",
    badge: "High ROI",
    author: "Salesfolk",
    description: "Results-driven approach with concrete examples",
    descriptionAr: "نهج قائم على النتائج مع أمثلة ملموسة",
    emails: 4,
    days: 7,
    schedule: [0, 2, 5, 7],
    stats: {
      avgOpenRate: 31.2,
      avgReplyRate: 12.1,
      usedCount: 1892,
    },
    structure: [
      { day: 0, subject: "Problem identification", type: "problem" },
      { day: 2, subject: "Case study with numbers", type: "case_study" },
      { day: 5, subject: "Another case study", type: "case_study" },
      { day: 7, subject: "Simple ask", type: "ask" },
    ],
    bestFor: ["E-commerce", "Real Estate", "Finance"],
    difficulty: "beginner",
  },
  {
    id: 3,
    name: "Problem-Solve Approach",
    nameAr: "نهج حل المشكلة",
    badge: "New",
    author: "Lemlist",
    description: "Empathy-first messaging with solution hints",
    descriptionAr: "رسائل تركز على التعاطف مع تلميحات للحل",
    emails: 3,
    days: 5,
    schedule: [0, 2, 5],
    stats: {
      avgOpenRate: 18.7,
      avgReplyRate: 5.1,
      usedCount: 834,
    },
    structure: [
      { day: 0, subject: "Identify pain point", type: "pain" },
      { day: 2, subject: "Agitate the problem", type: "agitate" },
      { day: 5, subject: "Present solution", type: "solution" },
    ],
    bestFor: ["Consulting", "Services", "B2B"],
    difficulty: "beginner",
  },
  {
    id: 4,
    name: "Quick Win Sequence",
    nameAr: "تسلسل الفوز السريع",
    badge: "Fast Results",
    author: "Josh Braun",
    description: "Ultra-short emails for busy executives",
    descriptionAr: "رسائل قصيرة جداً للمديرين التنفيذيين المشغولين",
    emails: 3,
    days: 6,
    schedule: [0, 3, 6],
    stats: {
      avgOpenRate: 28.3,
      avgReplyRate: 9.4,
      usedCount: 1567,
    },
    structure: [
      { day: 0, subject: "2-line question", type: "question" },
      { day: 3, subject: "One-sentence value", type: "value" },
      { day: 6, subject: "Yes/no question", type: "micro_commitment" },
    ],
    bestFor: ["C-Level", "Executives", "Busy Prospects"],
    difficulty: "advanced",
  },
  {
    id: 5,
    name: "Content-First Sequence",
    nameAr: "تسلسل المحتوى أولاً",
    badge: "Educational",
    author: "Aaron Ross",
    description: "Give value before asking for anything",
    descriptionAr: "أعط قيمة قبل أن تطلب أي شيء",
    emails: 4,
    days: 8,
    schedule: [0, 3, 5, 8],
    stats: {
      avgOpenRate: 26.1,
      avgReplyRate: 7.8,
      usedCount: 1234,
    },
    structure: [
      { day: 0, subject: "Free resource", type: "give" },
      { day: 3, subject: "More value", type: "give" },
      { day: 5, subject: "Insight + soft ask", type: "soft_ask" },
      { day: 8, subject: "Permission to continue", type: "permission" },
    ],
    bestFor: ["Thought Leadership", "Complex Sales", "Long Cycles"],
    difficulty: "intermediate",
  },
  {
    id: 6,
    name: "Compliment + Question",
    nameAr: "مجاملة + سؤال",
    badge: "Beginner Friendly",
    author: "Heather Morgan",
    description: "Flattery meets curiosity",
    descriptionAr: "المجاملة تلتقي بالفضول",
    emails: 3,
    days: 7,
    schedule: [0, 4, 7],
    stats: {
      avgOpenRate: 21.5,
      avgReplyRate: 6.3,
      usedCount: 2103,
    },
    structure: [
      { day: 0, subject: "Specific compliment + question", type: "compliment" },
      { day: 4, subject: "Follow-up with value", type: "value" },
      { day: 7, subject: "Breakup email", type: "breakup" },
    ],
    bestFor: ["Agencies", "Freelancers", "Small Business"],
    difficulty: "beginner",
  },
  {
    id: 7,
    name: "Re-engagement Sequence",
    nameAr: "تسلسل إعادة التفاعل",
    badge: "Revival",
    author: "Multiple",
    description: "Win back cold/frozen leads",
    descriptionAr: "استرجاع العملاء الباردين/المجمدين",
    emails: 2,
    days: 7,
    schedule: [0, 7],
    stats: {
      avgOpenRate: 12.8,
      avgReplyRate: 3.2,
      usedCount: 945,
    },
    structure: [
      { day: 0, subject: "Break-up email", type: "breakup" },
      { day: 7, subject: "Final goodbye", type: "final" },
    ],
    bestFor: ["Frozen Leads", "Inactive Contacts"],
    difficulty: "beginner",
  },
  {
    id: 8,
    name: "Event-Based Outreach",
    nameAr: "التواصل القائم على الأحداث",
    badge: "Timely",
    author: "Multiple",
    description: "Leverage news, funding, hiring",
    descriptionAr: "استفد من الأخبار والتمويل والتوظيف",
    emails: 3,
    days: 5,
    schedule: [0, 2, 5],
    stats: {
      avgOpenRate: 34.7,
      avgReplyRate: 14.2,
      usedCount: 1678,
    },
    structure: [
      { day: 0, subject: "Congrats on [event]", type: "congratulate" },
      { day: 2, subject: "Help with [related challenge]", type: "help" },
      { day: 5, subject: "Quick question", type: "question" },
    ],
    bestFor: ["Trigger-based", "Timely Outreach"],
    difficulty: "intermediate",
  },
]

export const byGoalTemplates = [
  { goal: "Book Meeting", templates: [1, 2, 4] },
  { goal: "Demo Request", templates: [2, 5] },
  { goal: "Generate Leads", templates: [1, 3, 6] },
  { goal: "Build Relationship", templates: [5] },
  { goal: "Re-engage Leads", templates: [7] },
  { goal: "Event-based", templates: [8] },
]

export const byIndustryTemplates = [
  { industry: "SaaS/Tech", templates: [1, 2, 4] },
  { industry: "E-commerce", templates: [2, 3] },
  { industry: "Real Estate", templates: [2, 6] },
  { industry: "Agencies", templates: [1, 6] },
  { industry: "Consulting", templates: [3, 5] },
]
