export const popularTemplates = [
  {
    id: 1,
    name: "3C Classic",
    nameAr: "3C كلاسيك",
    badge: "Most Popular",
    author: "Alex Berman",
    description: "Compliment + Case Study + Call to Action. The framework that booked meetings with Nike, Starbucks, and Morgan Stanley.",
    descriptionAr: "مجاملة + دراسة حالة + دعوة للعمل. الإطار الذي حجز اجتماعات مع نايكي وستاربكس ومورغان ستانلي.",
    emails: 3,
    days: 7,
    schedule: [0, 3, 7],
    stats: {
      avgOpenRate: "20-25",
      avgReplyRate: "9-12",
      usedCount: "3,000+",
    },
    structure: [
      {
        day: 0,
        subject: "Quick question about {{company}}",
        body: "Hi {{firstName}},\n\nBeen following {{company}} and love what you're doing — congrats on {{achievement}}!\n\nI specialize in {{yourService}} for companies like {{company}}. Recently, we helped {{caseName}} {{caseResult}}.\n\nWorth a quick chat?\n\n{{yourName}}",
        type: "initial",
      },
      {
        day: 3,
        subject: "Re: Quick question about {{company}}",
        body: "Hi {{firstName}},\n\nJust wanted to make sure my last email didn't get buried.\n\nWe helped {{caseName}} {{caseResult}} — happy to share how.\n\nWould a 15-minute call this week work?\n\n{{yourName}}",
        type: "follow_up",
      },
      {
        day: 7,
        subject: "Should I close your file?",
        body: "Hi {{firstName}},\n\nI haven't heard back, so I'll assume the timing isn't right.\n\nIf things change, feel free to reach out. I'm always happy to help.\n\nBest,\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["B2B", "SaaS", "Agencies", "Freelancers"],
    difficulty: "beginner",
  },
  {
    id: 2,
    name: "Pattern Interrupt",
    nameAr: "كسر النمط",
    badge: "High Open Rate",
    author: "Alex Berman",
    description: "Opens with unexpected personalization that breaks inbox pattern. Gets attention from busy executives.",
    descriptionAr: "يفتح بتخصيص غير متوقع يكسر نمط البريد الوارد. يجذب انتباه المديرين التنفيذيين المشغولين.",
    emails: 5,
    days: 14,
    schedule: [0, 3, 6, 10, 14],
    stats: {
      avgOpenRate: "25-30",
      avgReplyRate: "7-10",
      usedCount: "2,400+",
    },
    structure: [
      {
        day: 0,
        subject: "{{firstName}} - not a sales pitch",
        body: "Hi {{firstName}},\n\nI know you get dozens of pitches daily, so I'll be direct.\n\n{{specific_detail}} caught my eye — specifically how {{company}} approached {{achievement}}.\n\nOne question: are you handling {{pain_point}} in-house or outsourcing it?\n\nJust curious.\n\n{{yourName}}",
        type: "pattern_interrupt",
      },
      {
        day: 3,
        subject: "Thought you'd find this useful",
        body: "Hi {{firstName}},\n\nI put together a quick breakdown of how {{caseName}} solved {{pain_point}} and saved {{caseResult}}.\n\nHappy to send it over — no strings attached.\n\n{{yourName}}",
        type: "value",
      },
      {
        day: 6,
        subject: "{{company}} vs {{competitor}}",
        body: "Hi {{firstName}},\n\nCompanies in {{industry}} are shifting how they handle {{pain_point}}.\n\n{{caseName}} made the switch and saw {{caseResult}} within 3 months.\n\nWould it be worth 15 minutes to see if something similar could work for {{company}}?\n\n{{yourName}}",
        type: "social_proof",
      },
      {
        day: 10,
        subject: "Different angle",
        body: "Hi {{firstName}},\n\nI realize my previous emails focused on {{pain_point}}, but I'm also curious about {{another_pain}}.\n\nEither way, happy to share what we're seeing in {{industry}}.\n\n{{yourName}}",
        type: "angle_shift",
      },
      {
        day: 14,
        subject: "Closing the loop",
        body: "Hi {{firstName}},\n\nThis is my last note. I don't want to be that person who keeps emailing.\n\nIf {{pain_point}} becomes a priority down the road, I'm here.\n\nWishing {{company}} continued success.\n\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["C-Level", "Enterprise", "High-Value Targets"],
    difficulty: "intermediate",
  },
  {
    id: 3,
    name: "The Breakup Email",
    nameAr: "رسالة الوداع",
    badge: "Re-engagement",
    author: "Alex Berman",
    description: "The permission-based goodbye that gets the highest reply rate. Use when leads go cold.",
    descriptionAr: "رسالة الوداع القائمة على الإذن التي تحصل على أعلى معدل رد. استخدمها عندما يبرد العملاء المحتملون.",
    emails: 2,
    days: 5,
    schedule: [0, 5],
    stats: {
      avgOpenRate: "30-40",
      avgReplyRate: "12-18",
      usedCount: "1,800+",
    },
    structure: [
      {
        day: 0,
        subject: "Should I stop reaching out?",
        body: "Hi {{firstName}},\n\nI've sent a few emails and haven't heard back. Totally understand — you're busy.\n\nShould I:\n\nA) Stop emailing (no hard feelings)\nB) Try again in a few months\nC) Send over what we did for {{caseName}}\n\nJust hit reply with A, B, or C.\n\n{{yourName}}",
        type: "breakup",
      },
      {
        day: 5,
        subject: "Removing you from my list",
        body: "Hi {{firstName}},\n\nI'll take your silence as a 'not now' and remove you from my list.\n\nIf anything changes, you know where to find me.\n\nAll the best to you and the {{company}} team.\n\n{{yourName}}",
        type: "final",
      },
    ],
    bestFor: ["Cold Leads", "No Response", "Re-engagement"],
    difficulty: "beginner",
  },
  {
    id: 4,
    name: "4T Framework",
    nameAr: "إطار 4T",
    badge: "Psychology-Based",
    author: "Josh Braun",
    description: "Trigger + Think + Third-party + Talk. Built on buyer psychology to start real conversations.",
    descriptionAr: "محفز + تفكير + طرف ثالث + حديث. مبني على علم نفس المشتري لبدء محادثات حقيقية.",
    emails: 3,
    days: 7,
    schedule: [0, 3, 7],
    stats: {
      avgOpenRate: "25-35",
      avgReplyRate: "10-15",
      usedCount: "2,800+",
    },
    structure: [
      {
        day: 0,
        subject: "Noticed something about {{company}}",
        body: "Hi {{firstName}},\n\n{{specific_detail}}.\n\nHow are you currently handling {{pain_point}}?\n\n{{caseName}} faced the same challenge. With our help, they {{caseResult}} — without {{sacrifice}}.\n\nNo rush, but is this worth a conversation?\n\n{{yourName}}",
        type: "initial",
      },
      {
        day: 3,
        subject: "Quick thought for {{company}}",
        body: "Hi {{firstName}},\n\nI mentioned how {{caseName}} {{caseResult}}.\n\nHere's the part most people miss: they did it without {{sacrifice}}.\n\nWould it make sense to see if something similar could work at {{company}}?\n\n{{yourName}}",
        type: "follow_up",
      },
      {
        day: 7,
        subject: "Not the right time?",
        body: "Hi {{firstName}},\n\nI get it — priorities shift. I'll step back for now.\n\nIf {{pain_point}} moves up the list, I'd love to share what's working for companies like {{caseName}}.\n\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["B2B", "SaaS", "Professional Services"],
    difficulty: "intermediate",
  },
  {
    id: 5,
    name: "The Without Story",
    nameAr: "قصة بدون",
    badge: "Simple & Clear",
    author: "Josh Braun",
    description: "Explain your value in 7 seconds: 'With A, you do B, and C happens without D.' Stories stick, facts forget.",
    descriptionAr: "اشرح قيمتك في 7 ثوانٍ: 'مع أ، تفعل ب، ويحدث ج بدون د.' القصص تبقى، الحقائق تُنسى.",
    emails: 3,
    days: 7,
    schedule: [0, 4, 7],
    stats: {
      avgOpenRate: "20-28",
      avgReplyRate: "8-12",
      usedCount: "2,200+",
    },
    structure: [
      {
        day: 0,
        subject: "{{firstName}}, quick story",
        body: "Hi {{firstName}},\n\nWith {{yourProduct}}, {{company}} can {{benefit}} without {{sacrifice}}.\n\n{{caseName}} did exactly that — {{caseResult}}.\n\nWorth a quick chat to see if this fits?\n\n{{yourName}}",
        type: "initial",
      },
      {
        day: 4,
        subject: "The story behind {{caseName}}",
        body: "Hi {{firstName}},\n\nBefore {{caseName}} used our approach, they were spending {{oldWay}}.\n\nNow they {{newWay}} — without {{sacrifice}}.\n\nWould you like to see how?\n\n{{yourName}}",
        type: "follow_up",
      },
      {
        day: 7,
        subject: "Last one from me",
        body: "Hi {{firstName}},\n\nI'll keep this short: if {{pain_point}} is costing {{company}} time, I have a solution that works without {{sacrifice}}.\n\nIf not the right time, no worries at all.\n\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["Any Industry", "Simple Products", "Quick Pitch"],
    difficulty: "beginner",
  },
  {
    id: 6,
    name: "Referral Request",
    nameAr: "طلب إحالة",
    badge: "Enterprise",
    author: "Aaron Ross",
    description: "The Predictable Revenue method: ask executives for an internal referral. Best for large companies.",
    descriptionAr: "طريقة الإيرادات المتوقعة: اطلب من المديرين التنفيذيين إحالة داخلية. الأفضل للشركات الكبيرة.",
    emails: 3,
    days: 10,
    schedule: [0, 5, 10],
    stats: {
      avgOpenRate: "40-50",
      avgReplyRate: "5-13",
      usedCount: "3,500+",
    },
    structure: [
      {
        day: 0,
        subject: "Quick question, {{firstName}}",
        body: "Hi {{firstName}},\n\nI noticed {{company}} {{specific_detail}}.\n\nWould you be able to point me to whoever handles {{function}} at {{company}}? I'd love to share how we helped {{caseName}} {{caseResult}}.\n\nThanks for your time.\n\n{{yourName}}",
        type: "referral",
      },
      {
        day: 5,
        subject: "Re: Quick question",
        body: "Hi {{firstName}},\n\nJust circling back on my note below. I know you're busy — even a quick pointer to the right person would be really helpful.\n\n{{yourName}}",
        type: "follow_up",
      },
      {
        day: 10,
        subject: "Wrong person?",
        body: "Hi {{firstName}},\n\nI may have the wrong contact. If there's someone better to speak with about {{function}}, I'd appreciate the redirect.\n\nIf not, no worries — thanks for your time.\n\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["Enterprise", "Large Companies", "B2B"],
    difficulty: "beginner",
  },
  {
    id: 7,
    name: "Value Proposition",
    nameAr: "عرض القيمة",
    badge: "Direct",
    author: "Aaron Ross",
    description: "Get straight to the point. State your value in the first sentence. Respects busy people's time.",
    descriptionAr: "ادخل في الموضوع مباشرة. اذكر قيمتك في الجملة الأولى. يحترم وقت الأشخاص المشغولين.",
    emails: 4,
    days: 10,
    schedule: [0, 3, 7, 10],
    stats: {
      avgOpenRate: "20-30",
      avgReplyRate: "6-10",
      usedCount: "2,600+",
    },
    structure: [
      {
        day: 0,
        subject: "{{pain_point}} at {{company}}?",
        body: "Hi {{firstName}},\n\nWe help {{industry}} companies {{benefit}}.\n\n{{caseName}} saw {{caseResult}} after working with us.\n\nWould it make sense to chat for 15 minutes this week?\n\n{{yourName}}",
        type: "initial",
      },
      {
        day: 3,
        subject: "Re: {{pain_point}} at {{company}}",
        body: "Hi {{firstName}},\n\nJust wanted to bump this up. The offer to show how {{caseName}} achieved {{caseResult}} still stands.\n\nHappy to work around your schedule.\n\n{{yourName}}",
        type: "follow_up",
      },
      {
        day: 7,
        subject: "How {{caseName}} solved this",
        body: "Hi {{firstName}},\n\nHere's a quick summary of what {{caseName}} did:\n\nProblem: {{pain_point}}\nSolution: {{yourService}}\nResult: {{caseResult}}\n\nWant to see if we can replicate this for {{company}}?\n\n{{yourName}}",
        type: "social_proof",
      },
      {
        day: 10,
        subject: "Closing the loop, {{firstName}}",
        body: "Hi {{firstName}},\n\nI'll take your silence as a 'not right now.' Totally fine.\n\nWhen {{pain_point}} becomes a priority, feel free to reach out.\n\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["SMB", "Startups", "Direct Sales"],
    difficulty: "beginner",
  },
  {
    id: 8,
    name: "Pain Point Storytelling",
    nameAr: "سرد نقاط الألم",
    badge: "Highest Reply Rate",
    author: "Salesfolk (Heather Morgan)",
    description: "Tell your prospect's problem as a story. Builds emotional connection. 16-35% reply rates.",
    descriptionAr: "اسرد مشكلة العميل المحتمل كقصة. يبني اتصالاً عاطفياً. معدلات رد 16-35%.",
    emails: 4,
    days: 10,
    schedule: [0, 3, 7, 10],
    stats: {
      avgOpenRate: "25-35",
      avgReplyRate: "16-25",
      usedCount: "1,500+",
    },
    structure: [
      {
        day: 0,
        subject: "Quick thought about {{company}}'s {{area}}",
        body: "Hi {{firstName}},\n\nWhen {{company}}'s customers search for {{product}}, are they finding you first — or {{competitor}}?\n\nMost {{industry}} companies lose customers at this stage without realizing it.\n\nWe helped {{caseName}} fix this and they saw {{caseResult}}.\n\nWould it make sense to chat about what we're seeing?\n\n{{yourName}}",
        type: "story",
      },
      {
        day: 3,
        subject: "How {{caseName}} fixed this exact problem",
        body: "Hi {{firstName}},\n\nI wanted to share a quick story.\n\n{{caseName}} was facing the same challenge with {{pain_point}}. After working together, they {{caseResult}} in just {{timeframe}}.\n\nThe approach was simple — happy to walk you through it.\n\n{{yourName}}",
        type: "case_study",
      },
      {
        day: 7,
        subject: "One idea for {{company}}",
        body: "Hi {{firstName}},\n\nI've been thinking about {{company}}'s situation with {{pain_point}}.\n\nOne thing that worked for {{caseName}}: {{specific_tactic}}.\n\nWorth trying? I can explain more on a quick call.\n\n{{yourName}}",
        type: "value",
      },
      {
        day: 10,
        subject: "My last note, {{firstName}}",
        body: "Hi {{firstName}},\n\nI'll keep this simple: if {{pain_point}} is costing {{company}} money, I have ideas that have worked for others in {{industry}}.\n\nIf now isn't the right time, I completely understand.\n\nAll the best,\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["E-commerce", "SaaS", "Competitive Markets"],
    difficulty: "advanced",
  },
  {
    id: 9,
    name: "8-Touch Persistence",
    nameAr: "8 لمسات مثابرة",
    badge: "Long Game",
    author: "Salesfolk (Heather Morgan)",
    description: "8 emails over 6 weeks. 32% of replies come after email #5. Persistence wins.",
    descriptionAr: "8 رسائل خلال 6 أسابيع. 32% من الردود تأتي بعد الرسالة رقم 5. المثابرة تفوز.",
    emails: 8,
    days: 42,
    schedule: [0, 3, 7, 12, 18, 25, 32, 42],
    stats: {
      avgOpenRate: "20-30",
      avgReplyRate: "10-20",
      usedCount: "1,200+",
    },
    structure: [
      {
        day: 0,
        subject: "Idea for {{company}}'s {{area}}",
        body: "Hi {{firstName}},\n\nI've been looking at how {{industry}} companies handle {{pain_point}} and had an idea for {{company}}.\n\nWe helped {{caseName}} {{caseResult}} — would love to share the approach.\n\nWorth a quick chat?\n\n{{yourName}}",
        type: "initial",
      },
      {
        day: 3,
        subject: "Re: Idea for {{company}}",
        body: "Hi {{firstName}},\n\nJust bumping my note from earlier this week. I think there's a real opportunity for {{company}} around {{pain_point}}.\n\nHappy to share more details whenever works.\n\n{{yourName}}",
        type: "follow_up",
      },
      {
        day: 7,
        subject: "{{caseName}}'s results with {{area}}",
        body: "Hi {{firstName}},\n\nQuick case study: {{caseName}} was struggling with {{pain_point}}. After working together, they {{caseResult}}.\n\nThe process took {{timeframe}} and required minimal effort on their end.\n\nWant to see if we can do the same for {{company}}?\n\n{{yourName}}",
        type: "case_study",
      },
      {
        day: 12,
        subject: "Different approach to {{pain_point}}",
        body: "Hi {{firstName}},\n\nI realize I've been focused on one angle. Here's another way to think about {{pain_point}}:\n\nMost {{industry}} companies are solving it the hard way. There's a simpler path.\n\nInterested in hearing more?\n\n{{yourName}}",
        type: "angle_shift",
      },
      {
        day: 18,
        subject: "Quick update",
        body: "Hi {{firstName}},\n\nWe just helped another {{industry}} company {{caseResult}}. Thought of {{company}} immediately.\n\nIf the timing is better now, I'd love to connect.\n\n{{yourName}}",
        type: "value",
      },
      {
        day: 25,
        subject: "Thought of {{company}} today",
        body: "Hi {{firstName}},\n\nSaw an article about {{industry}} trends and {{company}} came to mind.\n\nCompanies tackling {{pain_point}} early are seeing big results — like {{caseName}} who {{caseResult}}.\n\nStill open to a conversation?\n\n{{yourName}}",
        type: "social_proof",
      },
      {
        day: 32,
        subject: "One more thing",
        body: "Hi {{firstName}},\n\nI know I've been persistent — it's only because I genuinely think we can help {{company}} with {{pain_point}}.\n\nIf you'd prefer I stop reaching out, just say the word. No hard feelings.\n\n{{yourName}}",
        type: "follow_up",
      },
      {
        day: 42,
        subject: "Goodbye, {{firstName}}",
        body: "Hi {{firstName}},\n\nThis is my last email. I've enjoyed learning about {{company}} and wish you all the best.\n\nIf {{pain_point}} ever becomes a priority, you know where to find me.\n\nAll the best,\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["Enterprise", "Long Sales Cycles", "High-Value Deals"],
    difficulty: "intermediate",
  },
  {
    id: 10,
    name: "Icebreaker + Value",
    nameAr: "كاسر الجليد + قيمة",
    badge: "Most Personal",
    author: "Lemlist (Guillaume Moubeche)",
    description: "Ultra-personalized opening line based on research. Shows you care before you pitch.",
    descriptionAr: "سطر افتتاحي مخصص للغاية بناءً على البحث. يُظهر اهتمامك قبل أن تعرض.",
    emails: 4,
    days: 12,
    schedule: [0, 4, 8, 12],
    stats: {
      avgOpenRate: "30-40",
      avgReplyRate: "12-18",
      usedCount: "2,000+",
    },
    structure: [
      {
        day: 0,
        subject: "Loved your {{content_type}} about {{topic}}",
        body: "Hi {{firstName}},\n\n{{icebreaker}}\n\nSince you're focused on {{their_goal}}, I thought you'd find this interesting: we helped {{caseName}} {{caseResult}}.\n\nWorth a quick chat?\n\nEither way, keep up the great work!\n\n{{yourName}}",
        type: "icebreaker",
      },
      {
        day: 4,
        subject: "Something for {{company}}",
        body: "Hi {{firstName}},\n\nI put together a quick resource on {{topic}} that might help with {{their_goal}}.\n\nNo pitch — just thought it would be useful based on what {{company}} is working on.\n\n{{yourName}}",
        type: "value",
      },
      {
        day: 8,
        subject: "{{firstName}}, one more thought",
        body: "Hi {{firstName}},\n\nI keep coming back to what {{company}} is doing with {{area}}. There's a real opportunity here.\n\n{{caseName}} was in a similar spot and {{caseResult}}.\n\n15 minutes to explore this?\n\n{{yourName}}",
        type: "follow_up",
      },
      {
        day: 12,
        subject: "No worries, {{firstName}}",
        body: "Hi {{firstName}},\n\nI'll stop here. If the timing is ever right for {{their_goal}}, I'd love to help.\n\nKeep crushing it at {{company}}!\n\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["Agencies", "Consulting", "Creative Services"],
    difficulty: "intermediate",
  },
  {
    id: 11,
    name: "Multichannel Sequence",
    nameAr: "تسلسل متعدد القنوات",
    badge: "Advanced",
    author: "Lemlist (Guillaume Moubeche)",
    description: "Email + LinkedIn + Follow-up. Covers multiple channels for maximum visibility.",
    descriptionAr: "بريد إلكتروني + لينكد إن + متابعة. يغطي قنوات متعددة لأقصى رؤية.",
    emails: 5,
    days: 17,
    schedule: [0, 2, 5, 10, 17],
    stats: {
      avgOpenRate: "25-35",
      avgReplyRate: "8-15",
      usedCount: "1,800+",
    },
    structure: [
      {
        day: 0,
        subject: "{{firstName}}, quick question about {{area}}",
        body: "Hi {{firstName}},\n\nI came across {{company}} and noticed {{specific_detail}}.\n\nWe help {{industry}} companies {{benefit}} — would love to share how.\n\nWorth a quick chat?\n\n{{yourName}}",
        type: "initial",
      },
      {
        day: 2,
        subject: "(LinkedIn) Connected with {{firstName}}",
        body: "Hi {{firstName}},\n\nJust sent you a connection request on LinkedIn. I'd love to stay in touch and share insights about {{area}}.\n\nAlso dropped you an email earlier this week — let me know if it caught your eye.\n\n{{yourName}}",
        type: "linkedin_note",
      },
      {
        day: 5,
        subject: "Following up, {{firstName}}",
        body: "Hi {{firstName}},\n\nWanted to circle back on my earlier note about {{pain_point}}.\n\n{{caseName}} tackled the same challenge and {{caseResult}}.\n\nWould 15 minutes work to explore this?\n\n{{yourName}}",
        type: "follow_up",
      },
      {
        day: 10,
        subject: "Resource for {{company}}",
        body: "Hi {{firstName}},\n\nI put together a quick guide on how {{industry}} companies are solving {{pain_point}}.\n\nHappy to share — no strings attached.\n\n{{yourName}}",
        type: "value",
      },
      {
        day: 17,
        subject: "Last note from me",
        body: "Hi {{firstName}},\n\nI'll keep it simple: I think we can help {{company}} with {{pain_point}}, but I understand if the timing isn't right.\n\nThis is my last note — if things change, I'm here.\n\nAll the best,\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["Enterprise", "High-Value", "Multi-Touch"],
    difficulty: "advanced",
  },
  {
    id: 12,
    name: "Win-Back Sequence",
    nameAr: "تسلسل استعادة العملاء",
    badge: "Win Back",
    author: "Combined Best Practices",
    description: "Re-engage frozen leads who stopped responding. The goodbye email often gets the best reply rate.",
    descriptionAr: "أعد إشراك العملاء المحتملين المجمدين الذين توقفوا عن الرد. رسالة الوداع غالباً تحصل على أفضل معدل رد.",
    emails: 3,
    days: 10,
    schedule: [0, 5, 10],
    stats: {
      avgOpenRate: "20-30",
      avgReplyRate: "8-14",
      usedCount: "1,600+",
    },
    structure: [
      {
        day: 0,
        subject: "It's been a while, {{firstName}}",
        body: "Hi {{firstName}},\n\nWe connected a while back about {{pain_point}} but the timing wasn't right.\n\nA lot has changed since then — including {{newThing}}.\n\nWorth revisiting?\n\n{{yourName}}",
        type: "re_engage",
      },
      {
        day: 5,
        subject: "New results to share",
        body: "Hi {{firstName}},\n\nSince we last spoke, we helped {{caseName}} {{caseResult}}.\n\nIf {{pain_point}} is still on your radar, I'd love to share what's working now.\n\n{{yourName}}",
        type: "value",
      },
      {
        day: 10,
        subject: "Removing you from my list",
        body: "Hi {{firstName}},\n\nI'm cleaning up my contact list and wanted to check before removing you.\n\nIf {{pain_point}} is still relevant, just reply 'keep me' and I'll stay in touch.\n\nOtherwise, I wish you and {{company}} all the best.\n\n{{yourName}}",
        type: "breakup",
      },
    ],
    bestFor: ["Frozen Leads", "Old Lists", "Re-engagement"],
    difficulty: "beginner",
  },
  {
    id: 13,
    name: "Blank Canvas",
    nameAr: "قالب فارغ",
    badge: "Custom",
    author: "Start from Scratch",
    description: "Build your own campaign from scratch. Full control over every email.",
    descriptionAr: "ابنِ حملتك الخاصة من الصفر. تحكم كامل في كل بريد إلكتروني.",
    emails: 1,
    days: 0,
    schedule: [0],
    stats: {
      avgOpenRate: 0,
      avgReplyRate: 0,
      usedCount: 0,
    },
    structure: [
      {
        day: 0,
        subject: "",
        body: "",
        type: "initial",
      },
    ],
    bestFor: ["Custom", "Experienced Users"],
    difficulty: "any",
  },
]

export const byGoalTemplates = [
  { goal: "Book Meeting", templates: [1, 2, 4, 7] },
  { goal: "Demo Request", templates: [5, 7, 8] },
  { goal: "Generate Leads", templates: [1, 4, 5, 10] },
  { goal: "Build Relationship", templates: [10, 11] },
  { goal: "Re-engage Leads", templates: [3, 12] },
  { goal: "Enterprise Outreach", templates: [6, 9, 11] },
]

export const byIndustryTemplates = [
  { industry: "SaaS/Tech", templates: [1, 2, 4, 7] },
  { industry: "E-commerce", templates: [5, 8] },
  { industry: "Agencies", templates: [1, 6, 10] },
  { industry: "Consulting", templates: [4, 5, 10] },
  { industry: "Enterprise", templates: [6, 9, 11] },
]
